[versions]
springboot = "3.5.0"
junit = "5.12.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springboot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

micrometer-core = { module = "io.micrometer:micrometer-core" }
micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }

# Explicit declaration, but no version â€” version comes from Spring Boot BOM
logback-classic = { module = "ch.qos.logback:logback-classic" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }


